name: emilpriver/geni
description: Migrate your migrations using geni
branding:
  icon: database
  color: green
author: emilpriver

inputs:
  migrations_folder:
    required: false
    default: "./migrations"
  wait_timeout:
    required: false
    default: "30"
  migrations_table:
    required: false
    default: ""
  database_url:
    required: true
  database_token:
    default: ""
    required: false
runs: 
  using: 'docker'
  image: 'gcr.io/emilpriver/geni:latest-slim'
  env:
    DATABASE_MIGRATIONS_FOLDER: ${{ inputs.migrations_folder }}
    DATABASE_URL: ${{ inputs.database_url }}
    DATABASE_TOKEN: ${{inputs.database_token}}
    DATABASE_WAIT_TIMEOUT: ${{inputs.wait_timeout}}
    DATABASE_NO_DUMP_SCHEMA: "false"
    DATABASE_MIGRATIONS_TABLE: ${{inputs.migrations_table}}
