name: emilpriver/geni/migrate
description: Migrate your migrations using geni

inputs:
  migrations_folder:
    required: false
    default: "./migrations"
  wait_timeout:
    required: false
    default: "30"
  migrations_table:
    required: false
    default: ""

secrets:
  database_url:
    required: true
  database_token:
    default: ""
    required: false

runs:
  using: docker
  image: ghcr.io/emilpriver/geni:latest
  args:
    - run
    - up
  env:
    DATABASE_MIGRATIONS_FOLDER: ${{ inputs.migrations_folder }}
    DATABASE_URL: ${{ secrets.database_url }}
    DATABASE_TOKEN: ${{secrets.database_token}}
    DATABASE_WAIT_TIMEOUT: ${{inputs.wait_timeout}}
    DATABASE_NO_DUMP_SCHEMA: "false"
    DATABASE_MIGRATIONS_TABLE: ${{inputs.migrations_table}}
