name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest, macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install docker for macos
      if: startsWith(matrix.os, 'macos-')
      uses: douglascamata/setup-docker-macos-action@v1-alpha
    - name: Databases
      run: docker compose up -d
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
