name: Rust

on:
  pull_request:
  push:
    branches:
      - '*'
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install docker for macos
      if: startsWith(matrix.os, 'macos-')
      uses: douglascamata/setup-docker-macos-action@v1-alpha
    - name: Databases
      run: docker compose up -d
    - name: Run tests
      run: cargo test --verbose
  build-binary:
    name: build binaries
    needs: [test]
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        include:
          - os: linux
            image: ubuntu-latest
            arch: 386
            setup: sudo apt-get update && sudo apt-get install -qq gcc-i686-linux-gnu
            env:
              CC: i686-linux-gnu-gcc
              CXX: i686-linux-gnu-g++
          - os: linux
            image: ubuntu-latest
            arch: amd64
            env: {}
          - os: linux
            image: ubuntu-latest
            arch: arm
            setup: sudo apt-get update && sudo apt-get install -qq gcc-arm-linux-gnueabi
            env:
              CC: arm-linux-gnueabi-gcc
              CXX: arm-linux-gnueabi-g++
              GOARM: 6
          - os: linux
            image: ubuntu-latest
            arch: arm64
            setup: sudo apt-get update && sudo apt-get install -qq gcc-aarch64-linux-gnu
            env:
              CC: aarch64-linux-gnu-gcc
              CXX: aarch64-linux-gnu-g++
          - os: macos
            image: macos-latest
            arch: amd64
            env: {}
          - os: macos
            image: macos-latest
            arch: arm64
            env: {}
          - os: windows
            image: windows-latest
            arch: amd64
            env: {}
    name: Build (${{ matrix.os }}/${{ matrix.arch }})
    runs-on: ${{ matrix.image }}
    env: ${{ matrix.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1  
      - name: Install toolchains
        run: rustup update
      - name: Install deps
        run: |
          sudo apt install libssl-dev
      - name: Build
        run: cargo build --release --verbose
      - name: Package
        shell: bash
        run: |
          cp target/release/geni geni-${{matrix.arch}}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.arch}}
          path: geni-${{matrix.arch}}
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
            files: 'geni*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-docker:
    name: build and release docker
    needs: [build-binary]
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/geni:latest
