name: Test Github Action

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  test-github-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Databases
      run: docker compose up -d
    - name: create test migrations
      run: bash scripts/test-migrations.sh
    - name: Test migrations
      uses: emilpriver/geni@ci-test-4
      with:
        database_url: "mariadb://root:password@localhost:3307/app"
